// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI7r0B3g6OrAtAjps2saV_C8b_Tu66mhY',
    appId: '1:748419744417:web:620f6c78b1cc49e01fa6e0',
    messagingSenderId: '748419744417',
    projectId: 'josesilva1997-my-notes',
    authDomain: 'josesilva1997-my-notes.firebaseapp.com',
    storageBucket: 'josesilva1997-my-notes.firebasestorage.app',
    measurementId: 'G-RJ0SZSME0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_jAqVnsxi_GIPrcwqJu58HmXTQqETzNc',
    appId: '1:748419744417:android:3d28937ba8a2dd061fa6e0',
    messagingSenderId: '748419744417',
    projectId: 'josesilva1997-my-notes',
    storageBucket: 'josesilva1997-my-notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8TAQ_aDEMBltxw9B4nhddIxz2WVv5yaA',
    appId: '1:748419744417:ios:6ffa60fc9972713b1fa6e0',
    messagingSenderId: '748419744417',
    projectId: 'josesilva1997-my-notes',
    storageBucket: 'josesilva1997-my-notes.firebasestorage.app',
    iosBundleId: 'io.github.JoseSilva1997.fluttertutorial.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8TAQ_aDEMBltxw9B4nhddIxz2WVv5yaA',
    appId: '1:748419744417:ios:6ffa60fc9972713b1fa6e0',
    messagingSenderId: '748419744417',
    projectId: 'josesilva1997-my-notes',
    storageBucket: 'josesilva1997-my-notes.firebasestorage.app',
    iosBundleId: 'io.github.JoseSilva1997.fluttertutorial.myNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI7r0B3g6OrAtAjps2saV_C8b_Tu66mhY',
    appId: '1:748419744417:web:4fa0e543dee7667b1fa6e0',
    messagingSenderId: '748419744417',
    projectId: 'josesilva1997-my-notes',
    authDomain: 'josesilva1997-my-notes.firebaseapp.com',
    storageBucket: 'josesilva1997-my-notes.firebasestorage.app',
    measurementId: 'G-7E6CH727ZZ',
  );
}
